package com.ironmind.app.data

import androidx.room.testing.MigrationTestHelper
import androidx.test.platform.app.InstrumentationRegistry
import com.ironmind.app.data.local.IronMindDatabase
import com.ironmind.app.data.local.Migrations
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test

/**
 * Verifies real Room migrations against a database created at a past schema version, rather
 * than only ever testing against the latest in-memory schema (as [com.ironmind.app.WorkoutDaoTest]
 * does). This requires the exported schema JSON for the starting version
 * (`app/schemas/com.ironmind.app.data.local.IronMindDatabase/<version>.json`) to exist as an
 * androidTest asset (wired up in `app/build.gradle.kts` via `sourceSets.androidTest.assets`).
 *
 * That JSON is generated by Room's KSP processor on a successful build (`exportSchema = true` on
 * [IronMindDatabase]) and must be committed once produced. In an environment that has never
 * completed a build with network access to fetch the Android Gradle Plugin, `app/schemas/` won't
 * exist yet and this test will fail to find its starting schema — that is an environment gap to
 * close (run a build once, commit `app/schemas/`), not a defect in the migration itself.
 */
class MigrationTest {

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        IronMindDatabase::class.java,
    )

    @Test
    fun migrate4To5_addsPerformedAtIndexWithoutLosingData() {
        helper.createDatabase(TEST_DB, 4).apply {
            execSQL(
                "INSERT INTO exercises (id, name, muscleGroup, equipment, description, isCustom, " +
                    "instructions, imagePath, imageUrl, nameEs) VALUES " +
                    "(1, 'Back Squat', 'QUADS', 'BARBELL', NULL, 0, NULL, NULL, NULL, NULL)",
            )
            execSQL(
                "INSERT INTO workout_sessions (id, routineId, title, startedAt, endedAt, notes) " +
                    "VALUES (1, NULL, NULL, 1000, NULL, NULL)",
            )
            execSQL(
                "INSERT INTO set_logs (id, sessionId, exerciseId, setNumber, weightKg, reps, rpe, " +
                    "isWarmup, isCompleted, restSeconds, notes, performedAt) VALUES " +
                    "(1, 1, 1, 1, 100.0, 5, NULL, 0, 1, NULL, NULL, 1000)",
            )
            close()
        }

        // Passing every migration lets Room resolve the 4 -> 5 path itself; validateDroppedTables
        // = true also confirms the resulting schema matches what IronMindDatabase now expects.
        val migratedDb = helper.runMigrationsAndValidate(TEST_DB, 5, true, *Migrations.ALL)

        migratedDb.query("SELECT COUNT(*) FROM set_logs").use { cursor ->
            cursor.moveToFirst()
            assertEquals(1, cursor.getInt(0))
        }
        migratedDb.query(
            "SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'index_set_logs_performedAt'",
        ).use { cursor ->
            assertEquals(1, cursor.count)
        }
    }

    private companion object {
        const val TEST_DB = "migration-test"
    }
}
